# Generated by Django 6.0.1 on 2026-06-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventlogisticsassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='co_organizers',
        ),
    ]
