# Generated by Django 6.0.1 on 2026-06-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_co_organizers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='is_booked',
        ),
    ]
