# Generated by Django 6.0.1 on 2026-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_ban_reason_profile_is_banned_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('PASS_PUBLISHED', 'Passes Published'), ('VENUE_OVERRIDE', 'Venue Override'), ('CERT_UPLOADED', 'Certificate Uploaded'), ('REG_CANCELLED', 'Registration Cancelled'), ('STUDENT_BANNED', 'Student Banned'), ('STUDENT_UNBANNED', 'Student Unbanned'), ('LOGISTICS_ASSIGNED', 'Logistics Assigned'), ('PASS_PUBLISHED_ADMIN', 'Passes Published by Admin')], max_length=25),
        ),
    ]
