# Generated by Django 6.0.1 on 2026-06-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('PASS_PUBLISHED', 'Passes Published'), ('VENUE_OVERRIDE', 'Venue Override'), ('CERT_UPLOADED', 'Certificate Uploaded'), ('REG_CANCELLED', 'Registration Cancelled'), ('STUDENT_BANNED', 'Student Banned'), ('STUDENT_UNBANNED', 'Student Unbanned'), ('LOGISTICS_ASSIGNED', 'Logistics Assigned'), ('PASS_PUBLISHED_ADMIN', 'Passes Published by Admin'), ('PASS_RESET_REQUESTED', 'Password Reset Requested'), ('PASS_RESET_CONFIRMED', 'Password Reset Confirmed'), ('PASS_PUBLISHED_ADMIN', 'Passes Published by Admin'), ('PASS_DEACTIVATED', 'Passes Deactivated by Admin')], max_length=25),
        ),
    ]
